[server]
headless = true
runOnSave = true

[client]
toolbarMode = "minimal"
showErrorDetails = "none"

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#eb3f3b"
backgroundColor = "#f7f8fc"
secondaryBackgroundColor = "#ffffff"
textColor = "#252a34"
font = "sans serif"
