[server]
headless = true
runOnSave = true

[client]
toolbarMode = "minimal"
showErrorDetails = "none"

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#d94141"
backgroundColor = "#f7f7f6"
secondaryBackgroundColor = "#ffffff"
textColor = "#252a34"
font = "sans serif"
